class CreateItems < ActiveRecord::Migration[5.1]
  # this file is known as a 'migration' - it's how you create or change a database table.
  # this file was generated by running the following command in the command line:
    # rails generate migration CreateItems content:string due:datetime completed:boolean
    # I added the 'default: false' part on 'completed' manually

  # this migration is creating a table called 'items' with 5 columns, with specific data types:
    # 'content' - this is a 'string', relatively short text
    # 'due' - a date that you'll set when you create an item
    # 'status' - this is an integer column that will either be 0 or 1. all items
      # will start off as 0, and we'll be able to change them later
      # Rails provides a tool known as an 'enum' (enumerable) that maps these integers to
      # string values, so we'll be able to specify that '0' means 'incomplete', 1 means 'complete',
      # and if you wanted to you could add on and say '2' means 'pending', '3' means 'not gonna happen', etc.
    # "timestamps" this is a helper provided by Rails that creates 2 additional columns:
      # created_at and updated_at - they'll set themselves as you work.

  # when you're happy with how this file looks, you'll run:
    # bundle exec rake db:migrate
    # in the command line. that'll take this file and apply it to your database.

  def change
    create_table :items do |t|
      t.string :content
      t.datetime :due
      t.integer :status, default: 0

      t.timestamps
    end
  end
end
